raceCompleteDict = {("250", "1"): False,
                    ("250", "2"): False,
                    ("450", "1"): False,
                    ("450", "2"): False,
                    ("250", "HEAT", "1"): False,
                    ("250", "HEAT", "2"): False,
                    ("250", "LCQ"): False,
                    ("250", "MAIN"): False,
                    ("450", "HEAT", "1"): False,
                    ("450", "HEAT", "2"): False,
                    ("450", "SEMI", "1"): False,
                    ("450", "SEMI", "2"): False,
                    ("450", "LCQ"): False,
                    ("450", "MAIN"): False}

bubbleDict = {('450', 'HEAT'): 4,
              ('450', 'SEMI'): 5,
              ('450', 'LCQ'): 4,
              ('450', 'LAST CHANCE QUALIFIER'): 4,
              ('250', 'HEAT'): 9,
              ('250', 'LCQ'): 4,
              ('250', 'LAST CHANCE QUALIFIER'): 4}
